### ISSUE TITLE
TODO: 

### ISSUE THREAD

**Issue by RadianFord** [RadianFord/wro-updates#3]
- [x] Add + 20 all stats food
- [x] Plant System
- [x] Crimson Weapon Box
- [x] Light, Dark and Poison converter
- [x] Box of Crimson Weapon
- [x] Naght Twin Sword [13412 + 13413]
- [x] Elemental Sword
- [x] Boss Monsters Weapon
